name: danef_dictionary
description: A new Flutter project.

version: 1.0.0+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^0.5.1
  flutter_typeahead: ^1.8.7
  http: ^0.12.2
  json_annotation: ^3.0.1
  fancy_bottom_navigation:
    git:
      url: https://github.com/skquark/fancy_bottom_navigation.git
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  shared_preferences: ^0.5.8
  flutter_dotenv: ^2.1.0
  flutter_keyboard_visibility: ^3.2.1
  url_launcher: ^5.4.2
  share: ^0.6.3+6
  intl: ^0.16.1
  easy_localization: ^1.4.1
  page_transition: ^1.1.6
  loadmore: ^1.0.4
  flutter_html: ^1.0.0

dependency_overrides:
  flutter_svg: 0.18.0

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  test: ^1.5.1
  build_runner: ^1.0.0
  json_serializable: ^3.3.0
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - resources/langs/tr-TR.json
    - resources/langs/en-EN.json
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/animations/
    - .env
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
    - family: DidactGothic
      fonts:
        - asset: assets/fonts/DidactGothic-Regular.ttf