name: danef_dictionary
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_typeahead: ^1.7.0
  http: ^0.12.0+2
  json_annotation: ^2.0.0
  fancy_bottom_navigation:
    git:
      url: https://github.com/skquark/fancy_bottom_navigation.git
  sqflite: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: TextMeOne
      fonts:
        - asset: assets/fonts/TextMeOne-Regular.ttf