name: danef_dictionary
description: A new Flutter project.

version: 1.0.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_typeahead: ^1.7.0
  http: ^0.12.0+2
  json_annotation: ^2.0.0
  fancy_bottom_navigation:
    git:
      url: https://github.com/skquark/fancy_bottom_navigation.git
  sqflite: ^1.2.0
  path_provider: ^1.5.1
  shared_preferences: 0.5.6
  flutter_lottie: ^0.2.0
  fluttie: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/ic_launcher.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/animations/
  fonts:
    - family: TextMeOne
      fonts:
        - asset: assets/fonts/TextMeOne-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf